### ISSUE TITLE
Don't know

### ISSUE THREAD

**Issue by aleforfab** [kozmer/log4j-shell-poc#56]
Everything work but when I put the command in minecraft it does nothin

https://user-images.githubusercontent.com/54689365/147301814-c1bbfafc-cdb6-41d9-a17b-2c4cf521defc.mp4

g

**Comment by aleforfab** [comment]
<img width="956" alt="poc 2" src="https://user-images.githubusercontent.com/54689365/147301876-fcf6f7a4-88fb-4a42-89d5-351c98d11b3a.png">

**Comment by aleforfab** [comment]
When I check in the logs of the server it doesn't show the text so it probably run the command but their no respons on my side

**Comment by oSumAtrIX** [comment]
If the Minecraft server runs on windows this PoC will not work.

**Comment by svmorris** [comment]
It should not be a big issue to modify the POC to make it work on windows.
 Infact if you go back a few commits we had a version that supported Windows, we just had to remove it because it was quite buggy and un-maintained.

Otherwise running the server on a posix based system like Linux or macos hopefully fixes your issue.
