### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by NOcturnais** [kozmer/log4j-shell-poc#7]
When I send the command on a minecraft server, it crashes bruh

**Comment by kozmer** [comment]
Crashes what exactly? The MC server or client? We had issues where it was crashing the client too. Haven't looked more into this but I think it happens because it doesn't get a valid response from the server.

**Comment by NOcturnais** [comment]
the client

**Comment by NOcturnais** [comment]
![image](https://user-images.githubusercontent.com/32684737/146067635-1a44dd57-e642-4c12-b9e8-c496674dac77.png)

**Comment by NOcturnais** [comment]
first port is python's http server and second port is nlvp ncat server

**Comment by kozmer** [comment]
Do you get anything like this: 
![unknown](https://user-images.githubusercontent.com/87979263/146068398-89a06185-6227-4b3b-9b52-cb0a6fe034cb.png)

**Comment by svmorris** [comment]
Hi,
I ran into some similar issues while we were creating this POC. Your issue is most one of 2 things:

- 1 could be that your Minecraft server cannot reach your LDAP server.
- 2 if your LDAP server is being reached, then it possibly isn't returning anything valid. Is there any output on the LDAP server logs?


As a side not I want to ask that in order to make both of our lifes a little bit easier, could you please add a little bit more detail into your issues. It would be helpful for me a few more details including, but not limited entire logs of both your LDAP and Minecraft server, as well as what os and java version you are running.

**Comment by NOcturnais** [comment]
the minecraft server isn't running on my pc but yes I can give you poc's logs

**Comment by NOcturnais** [comment]
HTTP server
![image](https://user-images.githubusercontent.com/32684737/146068996-7ac10b15-975b-4bd1-a42a-50d007d7f47e.png)

POC
![image](https://user-images.githubusercontent.com/32684737/146069117-bb70178f-7eb0-4a59-880f-a4796e594a3f.png)

NETCAT
![image](https://user-images.githubusercontent.com/32684737/146069186-81cee221-3245-4d16-ba9f-e39be4ffc65b.png)

**Comment by NOcturnais** [comment]
I also opened these ports
![image](https://user-images.githubusercontent.com/32684737/146069362-355ad301-c0bd-4813-a1a9-5b4933891673.png)

**Comment by svmorris** [comment]
Hi,
Sorry, what do you mean about the server not running on your machine. Do you have access to pentest the minecraft server? If you do can you please send us some sort of proof of that before we can help you on. We do not want to aid or endorse our programs being used for any criminal activities.

**Comment by kozmer** [comment]
Okay, I see it gets the Exploit.class from the HTTP server, so it is working there so you should get a shell. My assumption is that its because you are port forwarding from your PUBLIC IP (which you probably shouldn't do) or its the server you are testing it on, thats why we asked for logs... You should probably set up a server to use instead of port forwarding..

As for what @svmorris  , please only test if you have permissions to do so.

**Comment by NOcturnais** [comment]
it's the server of a friend, I wan't to troll him but I don't have logs (I'll not use my public ip on another server lmao)
I'm going to try with a self hosted server

**Comment by NOcturnais** [comment]
![image](https://user-images.githubusercontent.com/32684737/146075559-f103b83a-2ae0-4002-a7dd-b7be63932f86.png)
I'm getting this error

**Comment by NOcturnais** [comment]
Understandable bcz the lib is not present on the server :/
