### ISSUE TITLE
Severe Threat: Trojan in index.jsp

### ISSUE THREAD

**Issue by quisquam88** [kozmer/log4j-shell-poc#72]
vulnerable-application/src/main/webapp/index.jsp line 7
contains a reference to a severe threat: Trojan:Script/Wacatac.B!ml

intentional?
remove it!

**Comment by kozmer** [comment]
So that is coming from this: `<link href="https://unpkg.com/tailwindcss@2.2.4/dist/tailwind.min.css" rel="stylesheet">`

Now that is the last thing I expected this alert to come from, considering this is an exploit.... 

Again, not intentional and is just a css file coming from a CDN. I have not checked this out but I would advise to run all exploits inside of a virtualized environment so your host wont be affected in case anything does happen.

**Comment by quisquam88** [comment]
Apologies: I made a wrong accusation.
Windows security comes upt with the threat, when I open "exploit.class". Changing the name in poc.py from "exploit" to "SomeClass" bypasses it.

**Comment by kozmer** [comment]
No worries :) I forgot that it was actually called Exploit.class to be honest so yeah, that in most cases would trigger Defender in itself..
